from common.frontendhelpers import *
from common.tracetype import *
import copy
import pdb
import numpy as np
import pandas as pd
import scipy.stats as sp_st


# ----------------------  get_reward_value() FUNCTION  -------------------
# get_reward_value accesses the reward value for a chosen action and trial
# number. The reward value was generated by the reward generator module

# inputs:   t1_epochs = rewards generated for action 1 and n trials, shape: 1xn
#           t2_epochs = rewards generated for action 2 and n trials, shape: 1xn
#           chosen_action = action selected for this trial
#           trial_num = current trial number
# outputs:  reward_val = reward value for action chosen in the current trial
# Notes :----------------------------------------------- (temporary, remov
# At some point we have to replace one variable/action(eg t1_epochs, t2_epochs ) by a single data structure.
# Change this function accordingly. We also have to decide if the format is n_trials x channels or the otherway round
# And maybe this function does not belong in init_params.py. It felt too
# specific for frontendhelpers.py too. Find a place

#def get_reward_value(t1_epochs, t2_epochs, chosen_action, trial_num):
def get_reward_value(t_epochs, chosen_action, trial_num):

    if chosen_action == "none":
        return 0
    #print("t_epochs",t_epochs)
    reward_val = t_epochs.iloc[trial_num][chosen_action]
    # print(reward_val)
    return reward_val


def get_reward_value_edit(chosen_action, trial_num, current_RT, target_RT, stop_list_trials_list): #scale_reward

    if trial_num not in stop_list_trials_list: #if ttype == 'go':
        
        if chosen_action == 'none': 
            reward_val = -100 
        else: 
            #reward_val = 100 - scale_reward*(np.abs(target_RT - current_RT)) Linear reward
            reward_val = 100 * np.exp(-np.abs(target_RT - current_RT)/(0.70*target_RT))  #(0.36*target_RT) #np.exp(-np.abs(target_RT - current_RT)/scale_reward)
    else: 

        if chosen_action == 'stop': 
            reward_val = 200 
        else: 
            reward_val = -100 
   
    return reward_val


# ----------------------helper_init_Q_support_params() FUNCTION  ---------
# helper_init_Q_support_params set the parameters for Q-learning algorithm with either the defaults or the values passed as arguments.
# inputs:   q_support = Q-learning related parameters sent as argument. This is a dictionary and allows setting only a subset of the parameters
#			bayes_unif_min, bayes_unif_max: min and max for the uniform distribution with reward_value as mean
#           bayes_H:
#           bayes_sF: variance for normal pdf
#           q_alpha: Q-value learning rate
#           dpmn_CPP_scale: CPP related scale to modulate dopamine level
#           reward_value: action related reward values, initialized but overwritten by rewards generated by reward generator module
#           chosen_action: chosen action this trial (overwritten every trial)
# outputs:  Q_support_params = Q-learning related parameters

def helper_init_Q_support_params(q_support=None, err_support=None):

    Q_support_params = ParamSet('Q_support_params',
                                {
                                 'q_alpha': 0.1, #0.1 CG   # 0.05 in original value, in working version 0.45
                                 #'dpmn_CPP_scale': 35.,
                                 'C_scale': 40., #40 
                                 #'dpmn_CPP_scale': 25.,
                                 'reward_value': -1.,
                                 'chosen_action': 1})

    err_support_params = ParamSet('err_support_params',
                                {
                                 'a': 0.5, 
                                 'b': 1})
    
    #print("q_support", q_support)
    if q_support is not None:

        Q_support_params = ModifyViaSelector(Q_support_params, q_support)

    if err_support is not None:

        err_support_params = ModifyViaSelector(err_support_params, err_support)

    #print(Q_support_params['C_scale'])    
    return Q_support_params, err_support_params

# ----------------------helper_update_Q_support_params() FUNCTION  -------
# helper_update_Q_support_params updates parameters for Q-learning algorithm on every trial
# inputs:   Q_support_params = Q-learning related parameters, maintains some constant values (set at the beginning of the simulation, and variables, which are updated every trial)
#			reward_val = updates Q_support_params.reward_value with the new reward value depending on current trial number and chosen action
#           chosen_action = updates Q_support_params.chosen_action with chosen action number in the current trial
# outputs:  Q_support_params = updated Q-learning related parameters


def helper_update_Q_support_params(
        Q_support_params,
        reward_val,
        chosen_action
        ):

    Q_support_params = untrace(Q_support_params)

    Q_support_params.reward_value = reward_val
    Q_support_params.chosen_action = chosen_action

    return Q_support_params

# ----------------------helper_init_Q_df() FUNCTION  ---------------------
# helper_init_Q_df initializes the Q-value data frame (n trials x k action channels). A new row is added to the dataframe every trial
# inputs:   actionchannels = dataframe related to the action channels. The
# action channels become the columns in a Q-value data frame.

# outputs:  Q_df = Q-value data frame


def helper_init_Q_df(actionchannels, Q_df_set=None, err_df_set=None):

    num_actions = len(actionchannels["action"])
    Q_df = pd.DataFrame(
        columns=[
            untrace(
                actionchannels.iloc[na]["action"]) for na in np.arange(num_actions)])
    Q_df = pd.concat([Q_df, pd.DataFrame({column: 0.5 for column in Q_df.columns},index=[0])], ignore_index=True)

    err_df = pd.DataFrame(
        columns=[
            untrace(
                actionchannels.iloc[na]["action"]) for na in np.arange(num_actions)])
    err_df = pd.concat([err_df, pd.DataFrame({column: 0 for column in err_df.columns},index=[0])], ignore_index=True)
    
    
    if Q_df_set is not None:
        Q_df = pd.DataFrame(
            columns=[
                untrace(
                    actionchannels.iloc[na]["action"]) for na in np.arange(num_actions)])
        Q_df = pd.concat([Q_df, pd.DataFrame({column: 0.5 for column in Q_df.columns},index=[0])], ignore_index=True)
        Q_df = untrace(ModifyViaSelector(Q_df, Q_df_set))

    if err_df_set is not None:
        err_df = pd.DataFrame(
            columns=[
                untrace(
                    actionchannels.iloc[na]["action"]) for na in np.arange(num_actions)])
        err_df = pd.concat([err_df, pd.DataFrame({column: 0 for column in err_df.columns},index=[0])], ignore_index=True)
        err_df = untrace(ModifyViaSelector(err_df, err_df_set))

    print('err_df', err_df)
    print('Q_df', Q_df)
    
    return Q_df, err_df

# ---------------------- helper_update_Q_df() FUNCTION  -------------------
# helper_update_Q_df updates the Q-value data frame (n trials x k action channels). A new row is added to the dataframe every trial
# inputs:   Q_df = current Q-value data frame. Stores q-values related to all action channels until the current trial
#			Q_support_params: mainly for the updated Q_support_params.reward_value and Q_support_params.chosen_action
#			dpmndefaults: To also update the dopamine release parameter dpmn_DAp according to the reward value
# outputs:  Q_df, Q_support_params,dpmndefaults = updated Q-value data
# frame, Q_support_params, dpmndefaults


def helper_update_Q_df(actionchannels, Q_df, err_df, Q_support_params, err_support_params, dpmndefaults, trial_num, current_RT, target_RT, timeout_RT, scale_power, scale_factor_stop, max_stop_amplitude, stop_list_trials_list, stop_amp, stop_iter):

    # Required to perform mathematical calculations with data frame values
    Q_support_params = untrace(Q_support_params)
    err_support_params = untrace(err_support_params)
    
    #assert isinstance(stop_amplitude_q,list)
    assert isinstance(max_stop_amplitude,list)
    stop_amplitude_q = np.zeros(len(stop_iter))

    #print('Q_df', Q_df)
    print('current_rt QVALUES:', current_RT)
    #print('Q_df.iloc[trial_num]', Q_df.iloc[trial_num])
    trial_wise_q_df = Q_df.iloc[trial_num]
    trial_wise_err_df = err_df.iloc[trial_num]
    
    #trial_wise_chosen_action = Q_support_params.chosen_action
    #print('Q_support_params.chosen_action[0]', Q_support_params.chosen_action[0])
    q_val_chosen = trial_wise_q_df[actionchannels["action"]]
    x_t = trial_wise_err_df[actionchannels["action"]]
    

    if trial_num not in stop_list_trials_list:
        
        q_error = max(Q_support_params.reward_value.values, 0)/100 - q_val_chosen.values
        q_val_updated = q_val_chosen.values + Q_support_params.q_alpha.values * q_error
    
    else:

        if Q_support_params.chosen_action[0] == 'stop':
            error = 0
        else:
            error = 1
        
        error_exp_updated = err_support_params.a.values * x_t.values + err_support_params.b.values * error
        #print('error_exp_updated', error_exp_updated)

    if trial_num not in stop_list_trials_list:

        da_inc_go = np.abs(q_error) * np.sign(current_RT - target_RT)*((np.abs(target_RT - current_RT)/(target_RT + current_RT))**scale_power)
        #print('type da_inc_go', type(da_inc_go))
        da_inc_stop = 0
    
    else:
        
        da_inc_stop = 0 #error_exp_updated * 0.001
        #print('x_t.values', x_t.values)
        #print('type x_t.values', type(x_t.values))
        #print('type da_inc_stop', type(da_inc_stop))
        da_inc_go = 0

    new_data_q = pd.DataFrame(Q_df[-1:].values, columns=Q_df.columns)
    new_data_err = pd.DataFrame(err_df[-1:].values, columns=err_df.columns)

    if trial_num not in stop_list_trials_list:
        new_data_q['reward_adj'] = max(Q_support_params.reward_value.values, 0)
        new_data_q['q_error_RPE'] = q_error
        #new_data_q['error_exp_stop'] = np.NaN
        
        #new_data_err['reward_adj'] = np.NaN
        #new_data_err['q_error_RPE'] = np.NaN
        new_data_err['x_t'] = np.NaN
        new_data_err['a'] = np.NaN
        new_data_err['b'] = np.NaN
        new_data_err['error'] = np.NaN
    
    else:
        new_data_q['reward_adj'] = np.NaN
        new_data_q['q_error_RPE'] = np.NaN 
        #new_data_q['error_exp_stop'] = error_exp_updated[0]
        
        #new_data_err['reward_adj'] = np.NaN
        #new_data_err['q_error_RPE'] = np.NaN 
        new_data_err['x_t'] = x_t.values[0]
        new_data_err['a'] = err_support_params.a.values[0]
        new_data_err['b'] = err_support_params.b.values[0]
        new_data_err['error'] = error
    
    new_data_q['da_inc'] = da_inc_go
    new_data_q['da_inc_scaled'] = da_inc_go * Q_support_params.C_scale
    new_data_q['target_rt'] = target_RT

    new_data_err['da_inc'] = da_inc_stop
    new_data_err['da_inc_scaled'] = da_inc_stop * Q_support_params.C_scale
    #new_data_err['target_rt'] = target_RT

    Q_df = pd.concat([Q_df,new_data_q])
    Q_df = Q_df.reset_index(drop=True)

    err_df = pd.concat([err_df,new_data_err])
    err_df = err_df.reset_index(drop=True)

    if trial_num not in stop_list_trials_list:
        
        Q_df.iloc[trial_num + 1][actionchannels["action"]] = q_val_updated  #Update q_val on go trials
        err_df.iloc[trial_num + 1][actionchannels["action"]] = err_df.iloc[trial_num][actionchannels["action"]]  #Keeping last err_val on go trials
    
    else:

        Q_df.iloc[trial_num + 1][actionchannels["action"]] = Q_df.iloc[trial_num][actionchannels["action"]] #Keeping last q_val on stop trials
        err_df.iloc[trial_num + 1][actionchannels["action"]] = error_exp_updated #Update x(t) = x(t+1) 
        
        
    if trial_num in stop_list_trials_list:

        if Q_support_params.chosen_action[0] == 'stop':

            for i in stop_iter: 
                stop_amplitude_q[i] = stop_amp[i] + scale_factor_stop * (max_stop_amplitude[i] - stop_amp[i])

    da_inc = da_inc_go + da_inc_stop
    print('da_go', da_inc_go) 
    print('da_inc_stop', da_inc_stop) 
    print('da_inc', da_inc) 
    
    dpmndefaults.dpmn_DAp = da_inc * Q_support_params.C_scale

    #print('dpmndefaults.dpmn_DAp qvalues.py', dpmndefaults.dpmn_DAp)

    return Q_df, err_df, Q_support_params, err_support_params, dpmndefaults, stop_amplitude_q
